### ISSUE TITLE
Remove 2s from Quasimodo

### ISSUE THREAD

**Issue by jayyoung** [strands-project/strands_3d_mapping#113]
Hi folks,
Quasimodo doesn't compile with the latest version of SOMA (using the update branch, which will be used in the deployment), as recently Hakan changed the message types and service names to remove all the 2s. Attempting to build gives the following output: 

````
-- +++ processing catkin package: 'quasimodo_brain'
-- ==> add_subdirectory(strands_3d_mapping/quasimodo/quasimodo_brain)
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "soma2_msgs" with
  any of the following names:

    soma2_msgsConfig.cmake
    soma2_msgs-config.cmake

  Add the installation prefix of "soma2_msgs" to CMAKE_PREFIX_PATH or set
  "soma2_msgs_DIR" to a directory containing one of the above files.  If
  "soma2_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  strands_3d_mapping/quasimodo/quasimodo_brain/CMakeLists.txt:4 (find_package)
````

This can be fixed with a quick find+replace. One for @jekekrantz  I think?

**Comment by nilsbore** [comment]
Ah, I'm a bit confused by the different branches there. We have a couple of upcoming PR:s that should fix this soon.

**Comment by nilsbore** [comment]
This is addressed in https://github.com/strands-project/strands_3d_mapping/pull/111, which I hope will be merged soon. I guess it relies on the soma and mongodb stuff being merged.

**Comment by nilsbore** [comment]
This is fixed now, closing.
