### ISSUE TITLE
semantic_map missing dependencies

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_3d_mapping#16]
```
CMake Error at scitos_3d_mapping/semantic_map/CMakeLists.txt:16 (rosbuild_prepare_qt4):
  Unknown CMake command "rosbuild_prepare_qt4".
```

**Comment by RaresAmbrus** [comment]
You need to install the qt-ros dependencies:

```
sudo apt-get install  ros-hydro-qt-ros
sudo apt-get install  ros-hydro-rqt
```

**Comment by hawesie** [comment]
Looks like `ros-hydro-qt-build` was missing at least.

These should be in the package.xml file so we can get them with rosdep.

**Comment by RaresAmbrus** [comment]
Weird, I didn't have that issue. Did you have the qt_ros dependencies installed?

**Comment by hawesie** [comment]
Yes, it looks like I had the two packages you listed already installed, but they didn't have that cmake macro which was missing.

**Comment by RaresAmbrus** [comment]
Oh ok. I'll add this to the package.xml. Is it fixed now?

**Comment by hawesie** [comment]
Yep, all compiles cleanly.

**Comment by cdondrup** [comment]
Exactly the same as #8.
If it works now, I think we can close the issues.

**Comment by RaresAmbrus** [comment]
Ok, I've added `ros-hydro-qt-build` and `ros-hydro-qt-ros` as dependencies in the package.xml and opened a pull request with these changes.

**Comment by RaresAmbrus** [comment]
@hawesie this was fixed a long time ago. Can you please close this issue?

**Comment by musiord** [comment]
Hi,
I installed all ros-qt packages and then I create a new package using the command 

> catkin_create_qt_pkg myProject

In the Package.xml the dependencies to qt_build is ok but when I try to compile I've the issue:

CMake Error at can_io/CMakeLists.txt:111 (rosbuild_prepare_qt4):
  Unknown CMake command "rosbuild_prepare_qt4".

Did someone has the same problem?

**Comment by RaresAmbrus** [comment]
@musiord I've never tried `catkin_create_qt_pkg`. If your `package.xml` and `CMakeLists.txt` are set up properly `catkin_make` should work.

**Comment by musiord** [comment]
Ok no pb, In fact I have a project using ROS and QT which is currently working except for Signal/Slot usage. I understand that there is a conflict between Qt and Boost for the usage of signals, so I want to disable Boost signals. I was thinking that the deffinition -DQT_NO_KEYWORDS in teh CMakeList.txt was doing this but infortunalety I seems to be the opposite :  

error: ‘emit’ was not declared in this scope

Tks for your help
