### ISSUE TITLE
[ekz-public-lib] Naming issue

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_3d_mapping#17]
I am getting loads of warnings when I launch completely disconnected packages (eg. scitos_bringup): 

```
WARNING: Package name "ekz-public-lib" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
```

I think this package needs renaming...

**Comment by jekekrantz** [comment]
Changed name to use underscores instead of dashes and added a pull request https://github.com/strands-project/scitos_3d_mapping/pull/18
