### ISSUE TITLE
Merge with 2d_navigation

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_3d_mapping#2]
Could this repository be merged with scitos_2d_navigation, and maybe turn scitos_2d_navigation into simply scitos_navigation?  The octomap.launch includes the 2d launch things anyway...

**Comment by marc-hanheide** [comment]
+1 for this. Then UOL will also add their navigation stuff in here.

**Comment by cburbridge** [comment]
@nilsbore Is this ok with you?

**Comment by RaresAmbrus** [comment]
@cburbridge Should be ok, I guess the planing and navigation tasks will always be executed on a 2D map (probably obtained from a projection of the 3D objects on the ground/robot plane).

**Comment by nilsbore** [comment]
Hey, I'm away on a few days vacation so sorry that I can't contribute further but seems good to me!

**Comment by hawesie** [comment]
I'm less clear on the need for this. I can foresee many potential future users of a relatively  standard 2D nav stack for the scitos. This will be very stable and the foundation of other apps. The 3D stuff seems less stable/more cutting edge to me. I'd hate to have students/newbies accidentally trying to compile all the 3D parts when all they want is to run the nav stack for the robot.

**Comment by marc-hanheide** [comment]
@hawesie is actually having a point there I haven't thought about. We already have students using the nav bits as they are, so this could indeed get a bit messy. I haven't thought properly, so -1 on this ;-)
