### ISSUE TITLE
wrong rosdep statement

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_3d_mapping#20]
This statement 

```
<build_depend>pcl</build_depend>
```

in  ekz-public-lib/package.xml is causing rosdep to fail because it looks for ros-hydro-pcl which doesn't exist, and according to the "non-markup" README.txt the file doesn't include `ros-hydro-perception-pcl` it maybe that the current line in package.xml is wrong?

**Comment by RaresAmbrus** [comment]
Fixed in 68b31906b32e650fd9aae46a2f9cbab89d27f3da.
