### ISSUE TITLE
Metric map ptu sweep pre-empt  

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_3d_mapping#23]
The metric map action server (`rosrun scitos_ptu ptu_action_server_metric_map.py`) needs to be preemptable.

**Comment by RaresAmbrus** [comment]
I'll look into it and implement it tomorrow.

**Comment by cburbridge** [comment]
Did you make any progress with this?

**Comment by RaresAmbrus** [comment]
Oh yeah, I opened a pull request for this a while ago.

**Comment by RaresAmbrus** [comment]
And I also merged it, so the action server should be preemptable now.

**Comment by cburbridge** [comment]
I tried with axclient, but it does not cancel...

**Comment by RaresAmbrus** [comment]
That's strange, I tested it out with a C++ client, first sending a goal and then cancelling it; seemed to work ok. I'll take another look.

**Comment by RaresAmbrus** [comment]
Sorry, it seems I hadn't merged my branch, just opened a pull request. I was checking another pull request by mistake yesterday. Also the underlying ptu_action_server is not preemptable at the moment, I'll modify that as well.

**Comment by RaresAmbrus** [comment]
@cburbridge I've opened a new pull request for scitos_drivers as well, where I changed the ptu_action_server in flir_pantilt to be preemptable. Can you please take a look before I merge it ? I have already merged the other pull request in scitos_apps, so both action servers should be preemptable now.

**Comment by cburbridge** [comment]
Super, thanks. A little while back I copied the flir ptu action server into scitos_ptu so that  simulation could use it too. At the end of the G4S run we should update that version with your changes to the one in scitos_drivers and remove the one from the drivers package. But, lets leave it as it is now because I don't know what is using the version in scitos_drivers, and the one in scitos_ptu is not launched by any launch files yet.

**Comment by RaresAmbrus** [comment]
I updated the scitos_ptu action server as well - I wasn't sure what was using what so I figured I might as well, since the code is almost identical. I've also (partially) tested it, seems to work ok.
