### ISSUE TITLE
cloud_merge and semantic_map don't link

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_3d_mapping#29]
Both produce the same linker error `/usr/bin/ld: cannot find -lmessage_store` if not build together with the rest of our system.
Just tried to build the repository in a custom workspace overlaying the strands workspace but got this error for both of the packages. Somehow it does not seem to find the message store if it's not in the same workspace.

**Comment by hawesie** [comment]
I think this is a problem with `ros_datacentre` not these packages. I see the same behaviour in other packages too. Can you do the following?
1. `rosed ros_datacentre CMakeLists.txt`
2. Change line 58 from `#LIBRARIES ros_datacentre` to `LIBRARIES message_store`
3. Try building again

Without this the libraries are not exposed as part of the catkin package.

If this works please pull request the change for the datacentre.

**Comment by RaresAmbrus** [comment]
@cdondrup I think this can be closed now.
