### ISSUE TITLE
Cloud_register failed during compilation

### ISSUE THREAD

**Issue by mudrole1** [strands-project/strands_3d_mapping#30]
I have fresh installation on my new laptop and I got following error when trying to compile cloud_register (using catkin_make --only-pkg-with-deps cloud_register)

```
In file included from /opt/strands/strands_catkin_ws/src/scitos_3d_mapping/cloud_register/src/ndt_main.cpp:11:0:
/opt/strands/strands_catkin_ws/src/scitos_3d_mapping/cloud_register/include/ndtRegistration.h: In static member function ‘static NdtRegistration<PointType>::CloudPtr NdtRegistration<PointType>::registerClouds(NdtRegistration<PointType>::CloudPtr, NdtRegistration<PointType>::CloudPtr, Eigen::Matrix4f&, Eigen::Matrix4f) [with PointType = pcl::PointXYZRGB, NdtRegistration<PointType>::CloudPtr = boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >, Eigen::Matrix4f = Eigen::Matrix<float, 4, 4>]’:
/opt/strands/strands_catkin_ws/src/scitos_3d_mapping/cloud_register/src/ndt_main.cpp:37:78:   instantiated from here
/opt/strands/strands_catkin_ws/src/scitos_3d_mapping/cloud_register/include/ndtRegistration.h:62:9: warning: ‘void pcl::Registration<PointSource, PointTarget, Scalar>::setInputCloud(const PointCloudSourceConstPtr&) [with PointSource = pcl::PointXYZRGB, PointTarget = pcl::PointXYZRGB, Scalar = float, pcl::Registration<PointSource, PointTarget, Scalar>::PointCloudSourceConstPtr = boost::shared_ptr<const pcl::PointCloud<pcl::PointXYZRGB> >]’ is deprecated (declared at /usr/include/pcl-1.7/pcl/registration/impl/registration.hpp:43): [pcl::registration::Registration::setInputCloud] setInputCloud is deprecated. Please use setInputSource instead. [-Wdeprecated-declarations]
/tmp/ccT7TgqF.s: Assembler messages:
/tmp/ccT7TgqF.s:4090: Error: no such instruction: `vfmadd312ss 4(%rsp),%xmm1,%xmm5'
```

(and a lot of similar lines as last one)

```
make[2]: *** [scitos_3d_mapping/cloud_register/CMakeFiles/cloud_register_ndt.dir/src/ndt_main.cpp.o] Error 1
make[1]: *** [scitos_3d_mapping/cloud_register/CMakeFiles/cloud_register_ndt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/tmp/cckxV9pF.s: Assembler messages:
/tmp/cckxV9pF.s:43027: Error: no such instruction: `vfnmadd312sd 64(%rdi),%xmm1,%xmm0'
/tmp/cckxV9pF.s:43030: Error: no such instruction: `vfnmadd312sd 40(%rdi),%xmm2,%xmm1'
make[2]: *** [scitos_3d_mapping/cloud_register/CMakeFiles/cloud_register_lib.dir/src/voxel_grid_covariance.cpp.o] Error 1
make[1]: *** [scitos_3d_mapping/cloud_register/CMakeFiles/cloud_register_lib.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed
```

Please let me know, if you need something more.

**Comment by nilsbore** [comment]
This looks like the problem with the AVX instructions on the new core processors and the old gcc that we're using. You have to compile some packages with compiler flag -mno-avx. It's possible to set that globally when invoking catkin_make but I don't remember how I did that, @ToMadoRe I think you told me how to do that, do you remember? We should put this in a wiki somewhere.

**Comment by cdondrup** [comment]
I asked the same in gitter the other day. here is Thomas answer:

```
catkin_make -DCMAKE_CXX_FLAGS=-mno-avx -DCMAKE_C_FLAGS=-mno-avx

and would be great if the ones writing packages with a CMake file setting these flags to very specific parameters like
set(CMAKE_CXX_FLAGS "-O4 -g -pg -Wunknown-pragmas -Wno-unknown-pragmas -Wsign-compare")
could change that to
set(CMAKE_CXX_FLAGS "-O4 -g -pg -Wunknown-pragmas -Wno-unknown-pragmas -Wsign-compare ${CMAKE_CXX_FLAGS}")
```

Didn't try it yet though.

**Comment by ToMadoRe** [comment]
yes, try `catkin_make --only-pkg-with-deps cloud_register -DCMAKE_CXX_FLAGS=-mno-avx -DCMAKE_C_FLAGS=-mno-avx`

However, as the package `cloud_register`overwrites these flags, you would first have to change the CMakeLists.txt file fof https://github.com/strands-project/scitos_3d_mapping/blob/hydro-devel/cloud_register/CMakeLists.txt#L4 to:
`set(CMAKE_CXX_FLAGS "-O4 -fPIC -std=c++0x -fpermissive  ${CMAKE_CXX_FLAGS}")`

**Comment by hawesie** [comment]
Please someone commit that change!

**Comment by mudrole1** [comment]
Thanks, it worked to me. @ToMadoRe will you commit it?

**Comment by ToMadoRe** [comment]
Okay, I will have a look at this. There are some other packages that would require this addition as well.

**Comment by mudrole1** [comment]
Actually I can do this, as I fix it in my laptop and I know the packages, which need this

**Comment by cdondrup** [comment]
Since I hate command line arguments when it comes to cmake, what about this:

```
include(CheckCCompilerFlag)

check_c_compiler_flag("-mno-avx" HAVE_FLAG_M_NO_AVX)
if(HAVE_FLAG_M_NO_AVX)
      set(CMAKE_CXX_FLAGS "-mno-avx ${CMAKE_CXX_FLAGS}")
endif()

set(CMAKE_CXX_FLAGS "-O4 -fPIC -std=c++0x -fpermissive ${CMAKE_CXX_FLAGS}")
```

Just tested it and on Linda it seems to work.
This should check if the compiler flag is available and if so adds it to the cmake flags.

**Comment by RaresAmbrus** [comment]
@mudrole1 thanks for fixing this! If there are any more issues I can look into it as well.

**Comment by mudrole1** [comment]
Btw, it is problem of these packages:
from scitos_3d_mapping:
cloud_register
ekz_public_lib
semantic_map

from strands_utils:
ransac_primitives
primitive_extraction

**Comment by RaresAmbrus** [comment]
If everything compiles you should commit it.

**Comment by mudrole1** [comment]
@RaresAmbrus it seems that larger discussion is needed as can be seen in #31 So I dont know what solution we will accept.

**Comment by RaresAmbrus** [comment]
@mudrole1 can we close this? I think we have a working solution for now.
