### ISSUE TITLE
preparation for first release

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_3d_mapping#33]
This repository needs a little restructuring according to the plans outlined in https://github.com/strands-project/strands_management/wiki/software-distribution

Most importantly, it should be renamed to `strands_3d_mapping` as it has nothing to do with scitos. Then it needs proper `package.xml` etc. 

Once this is complete, the repository's dependencies should be checked and it should be released as outlined in https://github.com/strands-project/strands_management/wiki/STRANDS-release-procedures

**Comment by marc-hanheide** [comment]
Are there any plans to release this anytime soon? I understand this would be part of the data gathering during the marathon? In that case it would have to be released, right?

**Comment by RaresAmbrus** [comment]
Yes, this should be released as well. Can I rename this repository or should I create a new one and merge things from here?

**Comment by marc-hanheide** [comment]
renaming is good

**Comment by RaresAmbrus** [comment]
@marc-hanheide renaming can easily be done from the repository settings tab, but I don't have the permission to do it. Can you please see if it works for you?

**Comment by marc-hanheide** [comment]
Yes. Sure. I can do it. What name please?

**Comment by RaresAmbrus** [comment]
I think we were saying `strands_3d_mapping`. Thanks.

**Comment by marc-hanheide** [comment]
done!

**Comment by RaresAmbrus** [comment]
@marc-hanheide to get jenkins to build this repository I should follow the instructions at:

https://github.com/strands-project/strands_management/wiki/STRANDS-software-packaging,-deployment,-and-testing-(using-Jenkins)

in particular the part about strands `rosdistro`, right ?

**Comment by marc-hanheide** [comment]
yes, but if you want a quick run through just join the rosdistro chat or tell me to put it on, I can do it for you.

**Comment by marc-hanheide** [comment]
So, what's your view? Release the beast?

**Comment by RaresAmbrus** [comment]
Yes definitely. But first I want to merge some bugfixes from my fork and do one test on the robot tomorrow. I think tomorrow afternoon/evening it should be ready for the release.

**Comment by RaresAmbrus** [comment]
@marc-hanheide  can you please try to release this once https://github.com/strands-project/strands_3d_mapping/pull/46 is merged as well?

**Comment by marc-hanheide** [comment]
I'm releasing this now for the first time

**Comment by marc-hanheide** [comment]
there are a few missing deps in the released packages (i.e. missing `<build_depends>` in the `package.xml`s: see http://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-metaroom-xml-parser_binarydeb_precise_amd64/2/console

and also some files are generated in the wrong place: http://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-semantic-map_binarydeb_precise_amd64/1/console

**Comment by marc-hanheide** [comment]
I do have another one for you: (http://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-metaroom-xml-parser_binarydeb_precise_amd64/3/console)

```
/tmp/buildd/ros-hydro-metaroom-xml-parser-0.0.2-0precise-20141111-1959/include/simpleXMLparser.h:4:33: fatal error: pcl_ros/point_cloud.h: No such file or directory
```

**Comment by marc-hanheide** [comment]
and a deprecation warning you might want to fix in http://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-semantic-map_binarydeb_precise_amd64/2/

```
include/ndtRegistration.h:63:9: warning: 
'void pcl::Registration::setInputCloud(const PointCloudSourceConstPtr&)
  [with PointSource = pcl::PointXYZRGB, PointTarget = pcl::PointXYZRGB, Scalar = float, pcl::Registration::PointCloudSourceConstPtr = boost::shared_ptr >]' 
  is deprecated (declared at /usr/include/pcl-1.7/pcl/registration/impl/registration.hpp:43): 

[pcl::registration::Registration::setInputCloud] setInputCloud is deprecated. 
Please use setInputSource instead. [-Wdeprecated-declarations]
```

**Comment by RaresAmbrus** [comment]
A question - shouldn't jenkins find these errors when I open a pull request?

**Comment by marc-hanheide** [comment]
nope... because in a pull request the repository is build "as a whole", i.e. if package A resolve a dependency in your repo, then it will also be resolved for package B as it's all one big `catkin_make`. For the release process your repo is taken apart into individual packages, causing those packages with missing dependencies to fail. I know that is a bit annoying, but that's the ROS infrastructure. I'm myself surprised that only the release builds check for deprecation of any API, that's something the devel builds should also check for.

**Comment by RaresAmbrus** [comment]
Ok, should be done in https://github.com/strands-project/strands_3d_mapping/pull/48. I had removed the dependency on `pcl_ros` in the `metaroom_xml_parser` but I forgot to remove the include in the class :X
Should be fixed now.

**Comment by marc-hanheide** [comment]
sorry... now there are a few deps missing in the `package.xml`'s. 

http://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-cloud-merge_binarydeb_precise_amd64/4/console

`/tmp/buildd/ros-hydro-cloud-merge-0.0.3-0precise-20141111-2100/include/cloud_merge_node.h:38:18: fatal error: room.h: No such file or directory`

Or is this probably header not being installed properly (install target for them missing)?

and 

http://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-metaroom-xml-parser_binarydeb_precise_amd64/5/console

`/tmp/buildd/ros-hydro-metaroom-xml-parser-0.0.3-0precise-20141111-2055/include/simpleXMLparser.h:10:19: fatal error: tf/tf.h: No such file or directory`

This looks as if `<build_depend>tf</build_depend>` is missing

**Comment by RaresAmbrus** [comment]
The first error `/tmp/buildd/ros-hydro-cloud-merge-0.0.3-0precise-20141111-2100/include/cloud_merge_node.h:38:18: fatal error: room.h: No such file or directory` is due to the fact that the `cloud_merge` package depends on the `semantic_map` package, an both are in this repository. 

I'll add tf in the package.xml of `metaroom_xml_parser`, that should fix the second error.

Btw is there any way I can do this locally and sort all the dependencies out before merging to the strands repo?

**Comment by marc-hanheide** [comment]
There is no easy way, but one sanity check is to first run `catkin_make install` and check that everything you expect is actually in install location. The you could create a second workspace that _uses_ the install tree (source the `install/setup.bash` instead of the `devel/setup.bash`).

From what I can see the problem with `/tmp/buildd/ros-hydro-cloud-merge-0.0.3-0precise-20141111-2100/include/cloud_merge_node.h:38:18: fatal error: room.h: No such file or directory` is due to the fact that you didn't install the headers in the right place in your `CMakeLists.txt` of `semantic_map`. When they are installed they go into `/opt/ros/hydro/include/semantic_map/room.h`, so in a subdir `semantic_map`. You are generally expected to give that name in your include statements for exported headers in ROS. Check https://github.com/strands-project/mongodb_store/blob/hydro-devel/mongodb_store/CMakeLists.txt and you see what I mean. People put their header in `include/<PKG_NAME>` and then install with 

```
install(DIRECTORY include/<PKG_NAME>/
  DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
)
```

and in their own code they include with

```
#include <PKG_NAME/room.h>
```

This is a pretty general principle that we should follow. Otherwise your include tree when you do `catkin_make install` (so in `install/`) will be different to the one under `devel/`.

Make sense?

**Comment by marc-hanheide** [comment]
again, this of course is not picked up by PR builds, as they only build devel and don't check that the install tree is correct.

**Comment by marc-hanheide** [comment]
just to add, this is the generated pkg-config file:

```
prefix=/opt/ros/hydro

Name: semantic_map
Description: Description of semantic_map
Version: 0.0.3
Cflags: -I/opt/ros/hydro/include
Libs: -L/opt/ros/hydro/lib 
Requires: message_runtime sensor_msgs std_msgs
```

So you see you need to prefix your include with `<PKG_NAME>`

**Comment by RaresAmbrus** [comment]
@marc-hanheide thanks to the explanation! I'll update the includes with `<PKG_NAME>`.

Also, I'm not sure if the following does anything, other than structuring the code. So for example, if my headers are in `semantic_map/include/semantic_map` (this is the way you've structured it in `mongodb_store`) and I do:

```
install(DIRECTORY include/semantic_map/
  DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
)
```

The headers will end up in `/opt/ros/hydro/include/semantic_map/`

On the other hand, if my headers are in `semantic_map/include` and I do:

```
install(DIRECTORY include/
  DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
)
```

The headers should still end up in `/opt/ros/hydro/include/semantic_map/` right? Or am I missing something here?

**Comment by marc-hanheide** [comment]
The difference in your code when you include with the package name. E.g you would use `#include <semantic_map/room.h>` which will now work with both, installed and locally. Imagine there would be another room.h anywhere in your include path.

**Comment by marc-hanheide** [comment]
It's like a namespace...

**Comment by RaresAmbrus** [comment]
Ok, so the difference is in the local build space, got it now. I've updated the repo and opened a pull request - https://github.com/strands-project/strands_3d_mapping/pull/50. Hopefully this fixes the include problem.

**Comment by cdondrup** [comment]
Did #50 fix it? Seems it built...

**Comment by RaresAmbrus** [comment]
Built and released. I think we can close this.
