### ISSUE TITLE
cannot find -lmessage_store

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_3d_mapping#34]
This is due to 

```
target_link_libraries(cloud_merge
   ${catkin_LIBRARIES}
   ${PCL_LIBRARIES}
   ${QT_LIBRARIES}
   ${Boost_LIBRARIES}
   mongoclient
   message_store
 )
```

, which is in the CMakeLists.txt files of `cloud_merge` and `semantic map`

As @marc-hanheide mentioned on Gitter, explicitly linking the message_store is wong:
"that should already be resolved via ${catkin_LIBRARIES}
if the mongodb_store_cpp_clientis defined as a required dep in find_package(catkin REQUIRED COMPONENTS roscpp rospy std_msgs sensor_msgs tf pcl_ros semantic_map image_geometry image_transport qt_build cloud_register mongodb_store_cpp_client)
and we see it is, so just remove the last two lines from the target_link_libraries(cloud_merge… block
"

Could the maintainer please fix this?

**Comment by RaresAmbrus** [comment]
I guess removing the explicit linking to mongodb should fix it.; I'm not sure why it was there in the first place. I'll take a look and fix it.

**Comment by marc-hanheide** [comment]
works now, does it?

**Comment by RaresAmbrus** [comment]
This is not fixed yet, I still have mongodb related issues when installing from apt-get. I did:

```
sudo apt-get remove --purge ros-hydro-mongodb-store*
```

and

```
sudo apt-get install ros-hydro-mongodb-store
```

When compiling I get this error:

```
fatal error: mongodb_store/message_store.h: No such file or directory
```

**Comment by marc-hanheide** [comment]
well... 
firstly, does the file exist (I presume yes)? 
secondly, please provide a link to your `CMakeLists.txt`

**Comment by RaresAmbrus** [comment]
The file isn't there in `/opt/ros/hydro/include/mongodb_store`

I checked with `dpkg-query -L ros-hydro-mongodb-store`, `message_store.h` isn't installed. 

Here's the `CMakeLists.txt`:

```
https://github.com/RaresAmbrus/scitos_3d_mapping/blob/hydro-devel/cloud_merge/CMakeLists.txt
```

**Comment by marc-hanheide** [comment]
now, that is really odd... Are you sure you ran `sudo apt-get update` beforehand?

**Comment by RaresAmbrus** [comment]
Yes, I did it again now just to double check ...

**Comment by marc-hanheide** [comment]
ok, please send me the output of `dpkg -l ros-hydro-mongodb-store`

I want to make sure you have the correct version. Maybe a stupid question, but you have set up our own repository as described here: https://github.com/strands-project-releases/strands-releases/wiki#using-the-strands-repository ?

If you'd be using the version from the official ROS distribution, they are slow updating so that one is very outdated and buggy.

**Comment by marc-hanheide** [comment]
you should see this:

```
Desired=Unknown/Install/Remove/Purge/Hold                                                                                                              
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend                                                                         
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)                                                                                             
||/ Name                            Version                         Description                                                                        
+++-===============================-===============================-==============================================================================     
ii  ros-hydro-mongodb-store         0.1.3-1precise-20141022-1104-+0 A package to support MongoDB-based storage and analysis for data from a ROS sy     
```

and it has the file in there.

**Comment by RaresAmbrus** [comment]
Here's the `dpkg -l ros-hydro-mongodb-store` output:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                                       Description
+++-=============================================-=============================================-==========================================================================================================
ii  ros-hydro-mongodb-store                       0.0.4-0precise-20140914-0011-+0000            A MongoDB based central store for data from a ROS system, eg. configurations, logged states, etc
```

It seems I have an older version, I guess it must be the one from ROS, since I haven't set up anything else and was just downloading this directly with `apt-get`. After adding the Strands repository I'm able to get the latest version which contains `message_store.h`. Thanks @marc-hanheide 

One more question: if I include `mongodb_store` in `CATKIN_DEPENDS` I get some linker errors, but if I remove it from `CATKIN_DEPENDS` everything compiles fine. Does that make sense?

**Comment by marc-hanheide** [comment]
nope... that doesn't make sense. Please refer to https://github.com/strands-project/mongodb_store/issues/103 for some discussion around this. Is it related to boost? You may want to try to put mongodb_store as the first in your `CMakeLists.txt` dependencies in `find_package(catkin REQUIRED COMPONENTS ...)` (also before boost).

As stated in https://github.com/strands-project/mongodb_store/issues/103 this is an annoying problem, but changing the order helped overcoming it

**Comment by RaresAmbrus** [comment]
I moved `mongodb` up the dependency list and the linker error were miraculously solved! :D 
Thanks @marc-hanheide.
