### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_3d_mapping#35]
In file included from /opt/strands/strands_catkin_ws/src/scitos_3d_mapping/cloud_merge/src/cloud_merge_node.cpp:1:0:
/opt/strands/strands_catkin_ws/src/scitos_3d_mapping/cloud_merge/include/cloud_merge_node.h:26:42: fatal error: semantic_map/RoomObservation.h: No such file or directory

**Comment by cdondrup** [comment]
That's the old, package build does not wait until messages are created bug. Use:

```
add_dependencies(cloud_merge ${catkin_EXPORTED_TARGETS})
```

in the `cloud_merge` `CMakeLists.txt` file.

**Comment by RaresAmbrus** [comment]
Thanks @cdondrup, I've corrected it in my branch. I'll merge it as soon as I figure out how to set up the `mongodb_store` dependency properly.

**Comment by RaresAmbrus** [comment]
Fixed in 6450d2eae7f33d5470b454690be3d59af7992e82. @ToMadoRe I think you can close this.

**Comment by ToMadoRe** [comment]
ok...we can re-open it anyway.
