### ISSUE TITLE
default machine name is set to left-cortex in ptu_sweep.launch

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_3d_mapping#59]
should probably be localhost

**Comment by Jailander** [comment]
but that is not the PTU sweep we are usng @ToMadoRe

**Comment by Jailander** [comment]
we are using @RaresAmbrus version

**Comment by ToMadoRe** [comment]
how do I get that? I thought we are not using source code?

**Comment by Jailander** [comment]
yes that is released, I'm not sure you will have to ask in the chat or @RaresAmbrus himself I lost track of it a few days ago with all the navigation bugs

**Comment by RaresAmbrus** [comment]
@ToMadoRe you don't have to use source code. The action server is in `scitos_ptu` and you run it with:

```
rosrun scitos_ptu ptu_action_server_metric_map.py
```
