### ISSUE TITLE
Needs ros-hydro-qt-ros but not documented

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_3d_mapping#8]
`sudo apt-get install ros-hydro-qt-ros` or even better as rosdep

**Comment by RaresAmbrus** [comment]
This is already mentioned on the wiki page for the Local Metric Maps:

https://github.com/strands-project/strands_management/wiki/Y1-Integration-Group-1-(Local-metric-maps):-April-4th-System

I still have to update the readme for the packages.

**Comment by RaresAmbrus** [comment]
@cdondrup can you please close this?
